# Generated by Django 2.0.7 on 2019-12-12 22:39

from django.db import migrations, models
import django.db.models.deletion
import fiction.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=32, verbose_name='作者')),
                ('author_detail', models.TextField(verbose_name='作者简介')),
                ('author_icon', models.FileField(default='icom/default.jpg', upload_to='icom/')),
            ],
            options={
                'verbose_name_plural': '作者表',
            },
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_content', models.TextField()),
                ('up_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fction_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64, verbose_name='分类名字')),
            ],
            options={
                'verbose_name_plural': '小说分类表',
            },
        ),
        migrations.CreateModel(
            name='Fiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiction_img', models.FileField(default='fiction_img/default.jpg', upload_to='fiction_img/')),
                ('ficiton', models.IntegerField(choices=[(0, '连载中'), (1, '已完结')], verbose_name='小说状态')),
                ('ficiton_name', models.CharField(max_length=64, verbose_name='小说名字')),
                ('detail', models.TextField(verbose_name='小说简介')),
                ('tuijian', models.IntegerField(verbose_name='推荐数量')),
                ('dashang', models.IntegerField(verbose_name='打赏数量')),
                ('dianji', models.IntegerField(default=0, verbose_name='点击数量')),
                ('char_number', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='字数(w)')),
            ],
            options={
                'verbose_name_plural': '小说表',
            },
        ),
        migrations.CreateModel(
            name='Fiction_catelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiction_catelog', models.CharField(max_length=64, verbose_name='小说章节')),
                ('centent', models.TextField(verbose_name='章节内容')),
            ],
            options={
                'verbose_name_plural': '小说章节表',
            },
        ),
        migrations.CreateModel(
            name='Fiction_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiction', models.ForeignKey(db_constraint=fiction.models.Fiction, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fiction_list', to='fiction.Fiction', verbose_name='小说外键')),
            ],
        ),
        migrations.CreateModel(
            name='Fiction_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32, verbose_name='标签名')),
            ],
            options={
                'verbose_name_plural': '小说标签表',
            },
        ),
    ]
