# Generated by Django 2.0.7 on 2019-12-12 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fiction_list',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fiction_list', to=settings.AUTH_USER_MODEL, verbose_name='用户外键'),
        ),
        migrations.AddField(
            model_name='fiction_catelog',
            name='category',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiction_catelog', to='fiction.Fction_category', verbose_name='小说分类'),
        ),
        migrations.AddField(
            model_name='fiction_catelog',
            name='fiction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiction_catelog', to='fiction.Fiction', verbose_name='小说外键'),
        ),
        migrations.AddField(
            model_name='fiction',
            name='author',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fiction', to='fiction.Author'),
        ),
        migrations.AddField(
            model_name='fiction',
            name='fiction_tag',
            field=models.ManyToManyField(to='fiction.Fiction_tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='fiction',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='fiction.Fiction'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fiction.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='author',
            name='author_user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
