# Generated by Django 2.0.7 on 2019-12-13 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiction', '0002_auto_20191212_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '小说评论表'},
        ),
        migrations.AlterModelOptions(
            name='fiction_list',
            options={'verbose_name_plural': '最近阅读'},
        ),
        migrations.AddField(
            model_name='author',
            name='author_gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='作者性别'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_icon',
            field=models.FileField(default='icom/default.jpg', upload_to='icom/', verbose_name='作者图片'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_user',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='是否是本网站用户'),
        ),
        migrations.AlterField(
            model_name='fiction',
            name='fiction_img',
            field=models.FileField(default='fiction_img/default.jpg', upload_to='fiction_img/', verbose_name='小说图片'),
        ),
    ]
