# Generated by Django 2.0.7 on 2019-12-13 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiction', '0003_auto_20191213_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='是否是本网站用户'),
        ),
    ]
