# Generated by Django 2.0.7 on 2019-12-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191212_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(default=True, unique=True, verbose_name='手机号'),
        ),
    ]
