# Generated by Django 2.0.7 on 2019-12-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191213_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='n_money',
            field=models.IntegerField(default=0, verbose_name='n币数量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='recommend_number',
            field=models.IntegerField(default=1, verbose_name='推荐票数量'),
        ),
    ]
