# Generated by Django 2.0.7 on 2019-12-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191213_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gold',
            field=models.IntegerField(default=0, verbose_name='金币'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='用户性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='n_money',
            field=models.IntegerField(default=0, verbose_name='书币数量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_icon',
            field=models.FileField(default='user_icon/default.jpg', upload_to='user_icon/', verbose_name='用户头像'),
        ),
    ]
