# Generated by Django 2.0.7 on 2019-12-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='标题')),
                ('link', models.CharField(max_length=64, verbose_name='链接')),
                ('image', models.ImageField(upload_to='bannerOne', verbose_name='图片链接')),
                ('info', models.TextField(verbose_name='轮播图简介')),
                ('order', models.IntegerField(verbose_name='显示顺序')),
            ],
            options={
                'verbose_name_plural': '轮播图表1',
            },
        ),
        migrations.CreateModel(
            name='BannerSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='标题')),
                ('link', models.CharField(max_length=64, verbose_name='链接')),
                ('image', models.ImageField(upload_to='bannerOne', verbose_name='图片链接')),
                ('info', models.TextField(verbose_name='轮播图简介')),
                ('order', models.IntegerField(verbose_name='显示顺序')),
            ],
            options={
                'verbose_name_plural': '轮播图表2',
            },
        ),
    ]
