# Generated by Django 2.0.7 on 2019-12-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(verbose_name='订单号')),
                ('pay_way', models.IntegerField(choices=[(0, '支付宝'), (1, '微信')])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('pey_status', models.IntegerField(verbose_name=((0, '未支付'), (1, '支付成功')))),
            ],
        ),
    ]
