# Generated by Django 2.0.7 on 2019-12-13 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '订单表'},
        ),
    ]
