# Generated by Django 2.0.7 on 2019-12-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_auto_20191213_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pey_status',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '支付成功')]),
        ),
    ]
